In [8]:
import numpy as np
import pandas as pd

In [27]:
ejercicios = ['1a', '1b', '2', '3', '4a', '4b', '4c']

In [28]:
respuestas = []
respuestas.append(['A', 'a'])                   # 1a
respuestas.append(np.array([3.141592])) # 1b
respuestas.append(np.array([1.,2.,4.]))         # 2
respuestas.append(np.ones((3,3)).flatten())     # 3
respuestas.append(['C', 'c'])                          # 4a
respuestas.append(np.array([0.023, .23]))       # 4b
respuestas.append('x^4')                        # 4c

In [29]:
respuestas

[['A', 'a'],
 array([3.141592]),
 array([1., 2., 4.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 ['C', 'c'],
 array([0.023, 0.23 ]),
 'x^4']

In [30]:
df = pd.DataFrame([respuestas], columns=ejercicios)
df

1a          1b                2  \
0  [A, a]  [3.141592]  [1.0, 2.0, 4.0]   

                                               3      4a             4b   4c  
0  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]  [C, c]  [0.023, 0.23]  x^4

In [35]:
df.to_parquet('__ans', compression='gzip')

In [36]:
df2 = pd.read_parquet('__ans')
df2

1a          1b                2  \
0  [A, a]  [3.141592]  [1.0, 2.0, 4.0]   

                                               3      4a             4b   4c  
0  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]  [C, c]  [0.023, 0.23]  x^4

In [15]:
from evaluacion import Ejercicio
ȩ = Ejercicio('', local=True)

In [16]:
ȩ.responde('1a')

= a


¡Tu respuesta es correcta!


In [17]:
ȩ.responde('4a')

= c


¡Tu respuesta es correcta!


In [18]:
ȩ.responde('4c', 'x^4 \sin(x)')

<IPython.core.display.Latex object>

None x^4


¡Tu respuesta es correcta!


In [19]:
x = np.array([1., 2., 4.0000])

In [20]:
ȩ.verifica('2', x)

¡Tu resultado es correcto!


In [21]:
z = np.array(3.141592)
z

array(3.141592)

In [22]:
ȩ.verifica('1b', z)

¡Tu resultado es correcto!


In [23]:
dir(ȩ)

['_Ejercicio__topic',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'local',
 'read',
 'responde',
 'verifica']

In [24]:
vars(ȩ)

{'_Ejercicio__topic': '', 'local': True}

In [38]:
ejercicios = ['1', '2', '3', '4A', '4B', '4C', '4D']
respuestas = []
respuestas.append(np.array([0.1450]))   # 1
respuestas.append(np.array([0.0196]))   # 2
respuestas.append(['C', 'c'])           # 3
respuestas.append(np.array([2.369007])) # 4A
respuestas.append(np.array([0.498646])) # 4a
respuestas.append(np.array([4.9e-09]))  # 4b
respuestas.append(np.array([1.1e-09]))  # 4c
ans_df = pd.DataFrame([respuestas], columns=ejercicios)
ans_df.to_parquet('__ans', compression='gzip')
ans_df

1         2       3          4A          4B         4C         4D
0  [0.145]  [0.0196]  [C, c]  [2.369007]  [0.498646]  [4.9e-09]  [1.1e-09]

In [39]:
ans_df2 = pd.read_parquet('__ans')
ans_df2

1         2       3          4A          4B         4C         4D
0  [0.145]  [0.0196]  [C, c]  [2.369007]  [0.498646]  [4.9e-09]  [1.1e-09]