# Python de cero a experto
**Autor:** Luis Miguel de la Cruz Salas

<a href="https://github.com/luiggix/Python_cero_a_experto">Python de cero a experto</a> by Luis M. de la Cruz Salas is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0?ref=chooser-v1">Attribution-NonCommercial-NoDerivatives 4.0 International</a>

**Objetivo general**
- Conocer a fondo las ventajas de la biblioteca *Numpy*.

**Objetivos particulares**
- Identificar algunas de las funciones más usadas de la biblioteca *Numpy*.
- Hacer énfasis en los métodos y conceptos que se aprenderán y en algunas cuestiones computacionales. 

## Contenido
- [1 - Numpy.](#1)
    - [1.1 - Corrección de Arreglos Simples.](#1-1)
    - [1.2 - Nota sobre número pseudoaleatorios.](#1-2)
    - [1.3 - Modificar el tipo de dato de los elementos del arreglo.](#1-3)
    - [1.4 - Arreglos multidimensionales.](#1-4)
    - [1.5 - Cambiando el *shape* de los arreglos.](#1-5)
    - [1.6 - Copias y vistas de arreglos.](#1-6)
    - [1.7 - Rebanadas (*slicing*).](#1-7)
    - [1.8 - Operaciones básicas entre arreglos.](#1-8)
    - [1.9 - Operaciones entre arreglos Booleanos.](#1-9)
    - [1.10 - Métodos de los arreglos.](#1-10)
    - [1.11 - Apilación y concatenación de arreglos.](#1-11)
    - [1.12 - Agregando dimensiones al arreglo.](#1-12)
    - [1.13 - Constantes.](#1-13)
    - [1.14 - Exportando e importando arreglos a archivos.](#1-14)

<a name='1'></a>
## *Numpy*

Es una biblioteca de Python que permite crear y gestionar arreglos multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel que operan sobre estos arreglos. El sitio oficial es https://numpy.org/

Para usar todas las herramientas de numpy debemos importar la biblioteca como sigue:

In [1]:
import numpy as np
np.version.version

'1.23.1'

In [2]:
# Función para obtener los atributos de arreglos
info_array = lambda x: print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size(bytes) : {x.itemsize} \n size(elements) : {x.size}')

<a name='1-1'></a>
### Creación de arreglos simples

Crear un arreglo de números del 1 al 10 usando:
`np.array`, `np.arange`, `np.linspace`, `np.zeros`, `np.ones`, `np.random.rand`

In [3]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x = np.arange(1,11,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


**Ojo** `np.arange()` acepta parámetros flotantes:

In [8]:
xf = np.arange(1, 11, 1.0)
xf

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
info_array(xf)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [10]:
xf = np.arange(0.3, 0.7, 0.12)
xf

array([0.3 , 0.42, 0.54, 0.66])

In [11]:
x = np.linspace(1,10,10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


**Ojo**: con `np.linspace` es posible generar un número exacto de elementos, por ejemplo:

In [13]:
xf = np.linspace(0.3, 0.7, 6)
xf

array([0.3 , 0.38, 0.46, 0.54, 0.62, 0.7 ])

In [14]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
for i,val in enumerate(x):
    x[i] = i+1 
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [17]:
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [19]:
for i,val in enumerate(x):
    x[i] = i+val 
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
x *= 2
x

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [21]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [22]:
x = np.random.rand(10)
info_array(x)
x

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


array([0.76978589, 0.80958305, 0.50678792, 0.43459138, 0.92738943,
       0.88401604, 0.90055759, 0.82344359, 0.56161959, 0.28247087])

In [23]:
x = np.random.rand(2,5)
info_array(x)
x

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 2 
 shape : (2, 5) 
 size(bytes) : 8 
 size(elements) : 10


array([[0.63270473, 0.46134126, 0.24548865, 0.40925356, 0.59150003],
       [0.93602002, 0.67611096, 0.16777464, 0.23444719, 0.6258697 ]])

<a name='1-2'></a>

### Nota sobre número pseudoaleatorios
No es posible generar números aleatorios con base en un algoritmo, solo se pueden
obtener números **pseudoaleatorios** (para obtener números aleatorios es necesario muestrear algún parámetro físico cuyo valor sea realmente aleatorio).

Las series de números aleatorios que se pueden generar en una computadora son secuencias deterministas a partir de un valor inicial, al que se llama semilla. Al fijar la semilla se fija completamente los valores de toda la serie.

In [24]:
np.random.seed(0)
print("Serie 1:", np.random.rand(3))
np.random.seed(3)
print("Serie 2:", np.random.rand(3))
np.random.seed(0)
print("Serie 3:", np.random.rand(3))

Serie 1: [0.5488135  0.71518937 0.60276338]
Serie 2: [0.5507979  0.70814782 0.29090474]
Serie 3: [0.5488135  0.71518937 0.60276338]


Se puede generar una serie de números aleatorios usando una semilla aleatoria. Por ejemplo:

In [25]:
import time
np.random.seed(int(time.time()))
np.random.rand(3)

array([0.19222796, 0.95819055, 0.30101728])

<a name='1-3'></a>

### Modificar el tipo de dato de los elementos del arreglo

In [26]:
x = np.linspace(1,10,10)
# La modificación afecta al arreglo 'y' pero no al arreglo 'x' (no es inplace)
y = x.astype(int)

In [27]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [28]:
info_array(y)

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [29]:
print(id(x), id(y))

139839376679824 139839376679920


In [30]:
print(x)
print(y)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1  2  3  4  5  6  7  8  9 10]


<a name='1-4'></a>
### Arreglos multidimensionales

In [31]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [32]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : complex128 
 dim   : 2 
 shape : (3, 2) 
 size(bytes) : 16 
 size(elements) : 6


In [33]:
x = np.array( [ [1,2], [3,4] ], dtype=complex )
x

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [34]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : complex128 
 dim   : 2 
 shape : (2, 2) 
 size(bytes) : 16 
 size(elements) : 4


In [35]:
x = np.array( [ [[1,2], [3,4]], [[5,6], [7,8]] ])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [36]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 2, 2) 
 size(bytes) : 8 
 size(elements) : 8


In [37]:
x = np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 2 
 shape : (10, 10) 
 size(bytes) : 8 
 size(elements) : 100


In [39]:
x = np.ones((4,3,2))
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [40]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 3 
 shape : (4, 3, 2) 
 size(bytes) : 8 
 size(elements) : 24


In [41]:
x = np.empty((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [42]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24


<a name='1-5'></a>
### Cambiando el `shape` de los arreglos
#### Función `reshape`

In [43]:
x = np.array([ [[ 1, 2, 3, 4],
                [ 5, 6, 7, 8],
                [ 9,10,11,12]],
               [[13,14,15,16],
                [17,16,19,20],
                [21,22,23,24]] ])
info_array(x)
print(f'x = \n {x}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24
x = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]]


In [44]:
y = x.reshape(6,4)
info_array(y)
print(f'y = \n {y}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 2 
 shape : (6, 4) 
 size(bytes) : 8 
 size(elements) : 24
y = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 16 19 20]
 [21 22 23 24]]


In [45]:
info_array(x)
print(f'x = \n {x} \n')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24
x = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]] 



In [46]:
y = x.reshape(24)
info_array(y)
print(f'y = \n {y}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (24,) 
 size(bytes) : 8 
 size(elements) : 24
y = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 16 19 20 21 22 23 24]


In [47]:
y = x.reshape(2,3,4)
info_array(y)
print(f'y = \n {y}')
print(f'x = \n {x}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24
y = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]]
x = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]]


In [48]:
# Otra manera
np.reshape(x, (6,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 16, 19, 20],
       [21, 22, 23, 24]])

In [49]:
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 16, 19, 20],
        [21, 22, 23, 24]]])

#### Atributo `shape` (inplace)

In [50]:
y.shape

(2, 3, 4)

In [51]:
y.shape = (6,4)
y.shape

(6, 4)

In [52]:
info_array(y)
print(f'y = \n {y}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 2 
 shape : (6, 4) 
 size(bytes) : 8 
 size(elements) : 24
y = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 16 19 20]
 [21 22 23 24]]


#### Creando un arreglo y modificando su `shape` al vuelo

In [53]:
x = np.arange(24).reshape(2,3,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
x = np.arange(1,25,1).reshape(2,3,4)
info_array(x)
x

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

<a name='1-6'></a>
### Copias y vistas de arreglos

In [55]:
x = np.array([1,2,3,4])
z = x  # z es un sinónimo de x, no se crea una copia!
print(id(z), id(x))
print(z is x)
print(x is z)

139839376729840 139839376729840
True
True


**Los objetos que son *mutables* se pasan por referencia a una función:**

In [56]:
def f(a):
    print(id(a))

print(id(x))
print(f(x))

139839376729840
139839376729840
None


#### Copia superficial o vista de un arreglo

In [57]:
z = x.view()
print(id(z), id(x))
print(z is x)
print(x is z)
print(z.base is x) # Comparten la memoria 
print(z.flags.owndata) # Propiedades de la memoria
print(x.flags.owndata) # Propiedades de la memoria

139839376730128 139839376729840
False
False
True
False
True


In [58]:
print(z.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [59]:
z.shape =(2,2)
print(z.shape, z, sep = '\n')
print(x.shape, x, sep = '\n')

(2, 2)
[[1 2]
 [3 4]]
(4,)
[1 2 3 4]


In [60]:
z[1,1] = 1000
print(z.shape, z, sep = '\n')
print(x.shape, x, sep = '\n')

(2, 2)
[[   1    2]
 [   3 1000]]
(4,)
[   1    2    3 1000]


#### Copia completa de arreglos

In [61]:
z = x.copy()
print(id(z), id(x))
print(z is x)
print(x is z)
print(z.base is x) # Comparten la memoria 
print(z.flags.owndata) # Propiedades de la memoria
print(x.flags.owndata) # Propiedades de la memoria

139839376730320 139839376729840
False
False
False
True
True


In [62]:
print('z = ', z)
print('x = ', x)

z =  [   1    2    3 1000]
x =  [   1    2    3 1000]


In [63]:
z[3] = 4
print('z = ', z)
print('x = ', x)

z =  [1 2 3 4]
x =  [   1    2    3 1000]


#### Las rebanadas son vistas de arreglos
Las vistas de arreglos pueden ser útiles en ciertos casos, por ejemplo si tenemos un arreglo muy grande y solo deseamos mantener unos cuantos elementos del mismo, debemos hacer lo siguiente:

In [64]:
a = np.arange(int(1e5)) # Arreglo de 100000 elementos
b = a[:200].copy()      # Copia completa de 200 elementos de 'a'
del a                   # Eliminar la memoria que usa 'a'
b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

**Pero si usamos rebanadas, el comportamiento es distinto**:

In [65]:
a = np.arange(int(1e5)) # Arreglo de 100000 elementos
b = a[:200]             # Vista de 200 elementos de 'a'
b[0] = 1000
print('b = ', b)
print('a = ', a)

b =  [1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
 

<a name='1-7'></a>
### Rebanadas (slicing)

In [66]:
x = np.arange(0,10,1.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
x[:] # El arreglo completo

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
x[3:6] # Una sección del arreglo, de 3 a 5

array([3., 4., 5.])

In [69]:
x[2:9:2] # de 2 a 8, dando saltos de 2 en 2

array([2., 4., 6., 8.])

In [71]:
x[1:7:2] = 100 # modificando algunos elementos del arreglo
x

array([  0., 100.,   2., 100.,   4., 100.,   6.,   7.,   8.,   9.])

In [72]:
y = np.arange(36).reshape(6,6)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [73]:
y[1:4,:] # renglones de 1 a 3

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [74]:
y[:,1:5] # columnas de 1 a 4

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22],
       [25, 26, 27, 28],
       [31, 32, 33, 34]])

In [75]:
y[2:4,2:5] # seccion del arreglo

array([[14, 15, 16],
       [20, 21, 22]])

In [76]:
y[1:5:2,1:5:2] # sección del arreglo 
               # con saltos de 2

array([[ 7,  9],
       [19, 21]])

In [77]:
y[1:5:2,1:5:2] = 0 # Modificación de 
y                  # algunos elementos

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  0,  8,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18,  0, 20,  0, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

También es posible seleccionar elementos que cumplan cierto criterio.

In [77]:
y[y<25] # Selecciona los elementos del arreglo que son menores que 25

array([ 0,  1,  2,  3,  4,  5,  6,  0,  8,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18,  0, 20,  0, 22, 23, 24])

In [78]:
y[y%2==0] # Selecciona todos los elementos pares

array([ 0,  2,  4,  6,  0,  8,  0, 10, 12, 14, 16, 18,  0, 20,  0, 22, 24,
       26, 28, 30, 32, 34])

In [79]:
y[(y>8) & (y<20)] # Selecciona todos los elementos mayores que 8 y menores que 20

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [78]:
y[(y>8) & (y<20)] = 666
y

array([[  0,   1,   2,   3,   4,   5],
       [  6,   0,   8,   0, 666, 666],
       [666, 666, 666, 666, 666, 666],
       [666,   0,  20,   0,  22,  23],
       [ 24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35]])

In [79]:
z = np.nonzero(y == 666) # Determina los renglones y las columnas 
z                        # donde se cumple la condición.

(array([1, 1, 2, 2, 2, 2, 2, 2, 3]), array([4, 5, 0, 1, 2, 3, 4, 5, 0]))

In [84]:
z[0]
z[1]

array([4, 5, 0, 1, 2, 3, 4, 5, 0])

In [82]:
indices = list(zip(z[0], z[1])) # Genera una lista de coordenadas donde se cumple la condición.
indices

[(1, 4), (1, 5), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (3, 0)]

In [85]:
print(y[z]) # Imprime los elementos del arreglo 'y' usando las coordenadas de 'z'

[666 666 666 666 666 666 666 666 666]


<a name='1-8'></a>
### Operaciones básicas entre arreglos

In [80]:
v1 = np.array([2.3,3.1,9.6])
v2 = np.array([3.4,5.6,7.8])

In [81]:
(1/3)*v1 # Escalar por arreglo

array([0.76666667, 1.03333333, 3.2       ])

In [82]:
v1+v2 # Suma de arreglos

array([ 5.7,  8.7, 17.4])

In [83]:
v1-v2 # Resta de arreglos

array([-1.1, -2.5,  1.8])

In [84]:
v1*v2 # Multiplicación elemento a elemento

array([ 7.82, 17.36, 74.88])

In [85]:
v1/v2 # División elemento a elemento

array([0.67647059, 0.55357143, 1.23076923])

In [86]:
v1 ** 2 # Potencia de un arreglo

array([ 5.29,  9.61, 92.16])

In [87]:
v1 % 2  # Modulo de un arreglo

array([0.3, 1.1, 1.6])

In [88]:
10 * np.sin(v1) # Aplicación de una función matemática a cada elemento del arreglo

array([ 7.45705212,  0.41580662, -1.74326781])

In [89]:
v1 > 3 # Operación de comparación, devuelve un arreglo Booleano

array([False,  True,  True])

<a name='1-9'></a>
### Operaciones entre arreglos Booleanos

In [90]:
f = np.array([True, False, False, True])
r = np.array([False, True, False, True])

In [91]:
f & r

array([False, False, False,  True])

In [92]:
f | r

array([ True,  True, False,  True])

In [93]:
~f

array([False,  True,  True, False])

In [94]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [95]:
b[f]

array([0, 3])

In [97]:
b[f] = 100
b

array([100,   1,   2, 100])

<a name='1-10'></a>
### Métodos de los arreglos
Existe una larga lista de métodos definidos para los arreglos, vea más información <a href="https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-ndarray-methods">aquí</a>.

In [98]:
x = np.random.random(100) # arreglo de 100 números aleatorios entre 1 y 0
x

array([0.42540937, 0.08199528, 0.88496099, 0.32381277, 0.45089299,
       0.83042048, 0.74711282, 0.52620185, 0.13672565, 0.84522505,
       0.41633659, 0.02700198, 0.86874089, 0.05060088, 0.01035705,
       0.86524046, 0.18253511, 0.80002442, 0.5667958 , 0.07749154,
       0.16135519, 0.04789339, 0.40848212, 0.36881423, 0.8575511 ,
       0.87836948, 0.86501215, 0.71926682, 0.35621884, 0.02166241,
       0.82970508, 0.86967498, 0.37801171, 0.39526868, 0.66868771,
       0.55158522, 0.37197789, 0.74856897, 0.73716252, 0.76706072,
       0.87309585, 0.26415061, 0.79764737, 0.99505655, 0.6639731 ,
       0.17855885, 0.89527404, 0.13978085, 0.32977829, 0.4155706 ,
       0.66730478, 0.62383353, 0.86163547, 0.56710471, 0.20892521,
       0.27428501, 0.15224865, 0.25218857, 0.38981508, 0.07253246,
       0.11863786, 0.42867389, 0.20964763, 0.7180147 , 0.06089127,
       0.94715964, 0.44267164, 0.66521111, 0.03091784, 0.86979791,
       0.55996537, 0.67331132, 0.90612238, 0.44918226, 0.44991

In [99]:
x.max()

0.9950565524737125

In [100]:
x.sum()

48.417252941543296

In [101]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [102]:
x.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [103]:
x.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [104]:
np.transpose(x)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [105]:
np.flip(x) # Cambiar el orden de los elementos del arreglo

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [106]:
np.flip(x, axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [107]:
f1 = x.flatten() # Aplanar un arreglo
f1[0] = 1000
print(x)
print(f1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[1000    1    2    3    4    5    6    7    8    9]


In [108]:
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [109]:
f2 = x.ravel() # Aplanar un arreglo
f2[0] = 1000
print(x)
print(f1)

[[1000    1    2    3    4]
 [   5    6    7    8    9]]
[1000    1    2    3    4    5    6    7    8    9]


**Los arreglos deben ser compatibles para poder realizar las operaciones anteriores:**

In [110]:
a = np.arange(24).reshape(2,3,4)
b = np.arange(24).reshape(2,3,4)
a + b

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]])

In [111]:
c = np.arange(24).reshape(6,4)
a + c

ValueError: operands could not be broadcast together with shapes (2,3,4) (6,4) 

<a name='1-11'></a>
### Apilación y concatenación de arreglos

In [112]:
a = np.arange(4).reshape(2,2)
b = np.arange(4,8,1).reshape(2,2)
print(a)
print(b)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [113]:
np.vstack( (a, b) ) # Apilación vertical 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [114]:
np.hstack( (a, b) ) # Apilación horizontal 

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [115]:
x = np.arange(1,25,1).reshape(6,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [116]:
np.hsplit(x, 2) # División vertical en dos arreglos

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [117]:
np.vsplit(x, 2) #  División horizontal en dos arreglos

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

**Se recomienda revisar la función <a href="https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate">`np.concatenate` </a> para ver más opciones**

<a name='1-12'></a>
### Agregando dimensiones al arreglo

In [118]:
x = np.arange(1,11,1.)
info_array(x)
x

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [119]:
x.T

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [120]:
x_row = x[np.newaxis, :]
info_array(x_row)
x_row

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 2 
 shape : (1, 10) 
 size(bytes) : 8 
 size(elements) : 10


array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [121]:
x_row.T

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [122]:
x_col = x[:, np.newaxis]
info_array(x_col)
x_col

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 2 
 shape : (10, 1) 
 size(bytes) : 8 
 size(elements) : 10


array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [123]:
# Otra manera
x_row = np.expand_dims(x, axis=0)
x_col = np.expand_dims(x, axis=1)
print(x_row)
print(x_col)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


<a name='1-13'></a>
### Constantes

In [124]:
np.e

2.718281828459045

In [125]:
np.euler_gamma # Euler–Mascheroni constant

0.5772156649015329

In [126]:
np.pi

3.141592653589793

In [127]:
np.inf # Infinito

inf

In [128]:
#Por ejemplo
np.array([1]) / 0.

/tmp/ipykernel_24865/3182226453.py:2: RuntimeWarning: divide by zero encountered in divide
  np.array([1]) / 0.


array([inf])

In [129]:
np.nan # Not a Number: Valor no definido o no representable

nan

In [130]:
# Por ejemplo
np.sqrt(-1)

/tmp/ipykernel_24865/1910582514.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [131]:
np.log([-1, 1, 2])

/tmp/ipykernel_24865/55426429.py:1: RuntimeWarning: invalid value encountered in log
  np.log([-1, 1, 2])


array([       nan, 0.        , 0.69314718])

In [132]:
np.NINF  # Infinito negativo

-inf

In [133]:
# Por ejemplo
np.array([-1]) / 0.

/tmp/ipykernel_24865/3889258382.py:2: RuntimeWarning: divide by zero encountered in divide
  np.array([-1]) / 0.


array([-inf])

In [134]:
np.NZERO # Cero negativo

-0.0

In [135]:
np.PZERO # Cero positivo

0.0

<a name='1-14'></a>
### Exportando e importando arreglos a archivos

In [136]:
x = np.arange(1,25,1.0).reshape(6,4)
print(x)
np.savetxt('arreglo.csv', x, fmt='%.2f', delimiter=',', header='1,  2,  3,  4')

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]]


In [139]:
xf = np.loadtxt('arreglo.csv', delimiter=',')
xf

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.],
       [21., 22., 23., 24.]])

In [140]:
#Usando la biblioteca Pandas
import pandas as pd
df = pd.DataFrame(x)
df

0     1     2     3
0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0
2   9.0  10.0  11.0  12.0
3  13.0  14.0  15.0  16.0
4  17.0  18.0  19.0  20.0
5  21.0  22.0  23.0  24.0

In [141]:
df.to_csv('arreglo_PD.csv')

In [142]:
y = pd.read_csv('arreglo_PD.csv')
y

Unnamed: 0     0     1     2     3
0           0   1.0   2.0   3.0   4.0
1           1   5.0   6.0   7.0   8.0
2           2   9.0  10.0  11.0  12.0
3           3  13.0  14.0  15.0  16.0
4           4  17.0  18.0  19.0  20.0
5           5  21.0  22.0  23.0  24.0